config/routes.rb
BlackstarStdWeb::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :header_links
  
  resources :users, :only => [:show, :index]

  resources :main_sliders

  resources :product_images, :only => [:show, :create, :destroy]

  resources :product_categories

  resources :infos

  resources :products

  resources :product do
    resources :product_packages, :only => [:new, :destroy]
  end

  resources :product_packages, :only => [:create]

end

app/models/header_link.rb
class HeaderLink < ActiveRecord::Base
  attr_accessible :name

  extend FriendlyId
  friendly_id :name, :use => :slugged

  has_many :infos
end

app/controllers/header_links_controller.rb
class HeaderLinksController < ApplicationController
    load_and_authorize_resource

  # GET /header_links
  # GET /header_links.json
  def index
    @header_links = HeaderLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @header_links }
    end
  end

  # GET /header_links/1
  # GET /header_links/1.json
  def show
    @header_link = HeaderLink.find(params[:id])
    @infos = @header_link.infos

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @header_link }
    end
  end

  # GET /header_links/new
  # GET /header_links/new.json
  def new
    @header_link = HeaderLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @header_link }
    end
  end

  # GET /header_links/1/edit
  def edit
    @header_link = HeaderLink.find(params[:id])
  end

  # POST /header_links
  # POST /header_links.json
  def create
    @header_link = HeaderLink.new(params[:header_link])

    respond_to do |format|
      if @header_link.save
        format.html { redirect_to @header_link, :notice => 'Header link was successfully created.' }
        #format.json { render json: @header_link, status: :created, location: @header_link }
      else
        format.html { render :action => "new" }
        #format.json { render json: @header_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /header_links/1
  # PUT /header_links/1.json
  def update
    @header_link = HeaderLink.find(params[:id])

    respond_to do |format|
      if @header_link.update_attributes(params[:header_link])
        format.html { redirect_to @header_link, :notice => 'Header link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        #format.json { render json: @header_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /header_links/1
  # DELETE /header_links/1.json
  def destroy
    @header_link = HeaderLink.find(params[:id])
    @header_link.destroy

    respond_to do |format|
      format.html { redirect_to header_links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/header_links_helper.rb
module HeaderLinksHelper
end

app/views/header_links/_form.html.erb
<%= form_for(@header_link, :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>
    <legend><%= action %> Header</legend>

    <div class="control-group">
      <%= f.label 'Nama Header', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'textfield' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit 'Simpan', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/header_links/edit.html.erb
<div class="row">
  <div class="span12">
    <%= render :partial => 'form', :locals => { :action => "Ubah" } %>
  </div>
</div>

app/views/header_links/index.html.erb
<legend>Header</legend>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nama</th>
    </tr>
  </thead>
  <tbody>
    <% @header_links.each do |header_link| %>
      <tr>
        <td><%= header_link.name %></td>
        <td>
          <%= link_to 'Lihat', header_link, :class => 'btn btn-mini' %>
          <%= link_to 'Ubah', edit_header_link_path(header_link), :class => 'btn btn-mini' %>
          <%= link_to iconed_text('Hapus', 'icon-trash'), header_link, :confirm => 'Apakah anda yakin?', :method => :delete, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Tambah', new_header_link_path, :class => 'btn' if can? :create, @header_links %>

app/views/header_links/new.html.erb
<div class="row">
  <div class="span12">
    <%= render :partial => 'form', :locals => { :action => "Tambah" } %>
  </div>
</div>

app/views/header_links/show.html.erb
<% if can? :update, @header_link %>
  <div class="row">
    <div class="span6">
      <legend>Detail Link Utama</legend>
      <%
      data = []
      data << ["Nama Header", @header_link.name]
    %>

      <%= show(data).html_safe %>

      <%= link_to 'Ubah', edit_header_link_path(@header_link), :class => 'btn' %>
      <%= link_to 'Kembali', header_links_path, :class => 'btn' %>
    </div>
  </div>
<br/>
<br/>
<% end %>

<div class="row">
  <% @infos.each do |i| %>
    <div class="span12">
      <legend><%= i.title %></legend>

      <%= i.content.html_safe unless i.content.blank? %>
      <br/>

      <%= link_to 'Edit', edit_info_path(i), :class => 'btn' if can? :update, i %>
      <%= link_to iconed_text('Hapus', 'icon-trash'), i, :method => :delete, :confirm => 'Apakah anda yakin?', :class => 'btn btn-danger' if can? :destroy, i %>
    </div>
  <% end %>
</div>