config/routes.rb
BlackstarStdWeb::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :header_links
  
  resources :users, :only => [:show, :index]

  resources :main_sliders

  resources :product_images, :only => [:show, :create, :destroy]

  resources :product_categories

  resources :infos

  resources :products

  resources :product do
    resources :product_packages, :only => [:new, :destroy]
  end

  resources :product_packages, :only => [:create]

end

app/models/product.rb
class Product < ActiveRecord::Base
  # bt
  belongs_to :product_category

  has_many :products, :through => :product_packages
  has_many :parents, :class_name => 'ProductPackage', :foreign_key => 'child_id'
  has_many :childs, :class_name => 'ProductPackage', :foreign_key => 'parent_id'

  # ht
  has_many :product_images

  attr_accessible :name, :is_package, :description, :price, :product_category_id

  def triggered_save
    self.save
  end
  
  def triggered_update_attributes(product_array)
    self.update_attributes(product_array)
  end

  def triggered_destroy
    parents = self.parents
    parents.each do |parent|
      min = ProductPackage.where("parent_id = ? and child_id != ?", parent.parent_id, self.id).
        joins('LEFT JOIN products p ON product_packages.child_id = p.id').
        minimum('stock / product_packages.reduced_stocks')
      parent.parent.update_attribute(:stock, min)
      parent.destroy
    end

    self.destroy
  end

  def direct_childs
    childs.select("products.id, name, description, price, rent_price, stock, is_package, is_rented, stock_out, is_dimensional, reduced_stocks, parent_id").
      joins("LEFT JOIN products ON product_packages.child_id = products.id")

    #    where("parent_id = ?", product_id).
  end

  #  def self.stocks_in(date)
  #    find_by_sql("SELECT a.product_id as id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, stock, rented_qty, (stock - rented_qty) as remain
  #                  FROM (SELECT product_id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, SUM(a.stock) as stock
  #                        FROM product_stocks a
  #                             LEFT JOIN products b ON a.product_id = b.id
  #                        GROUP BY product_id) a
  #                       LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
  #                            FROM rented_products a
  #                            LEFT JOIN orders b ON a.order_id = b.id
  #                            WHERE b.delivery_date = '#{date}'
  #                            GROUP BY product_id) b ON a.product_id = b.product_id#")
  #  end

  scope :stocks, joins("LEFT JOIN product_stocks b ON products.id = b.product_id").
    group("b.product_id").
    select("products.id as id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, SUM(b.stock) as stock")
  scope :stocks_at, lambda { |date|
    stocks.joins("LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
                             FROM rented_products a
                             LEFT JOIN orders b ON a.order_id = b.id
                             WHERE '#{date}' BETWEEN b.delivery_date AND DATE_ADD(b.usage_date, INTERVAL (b.duration_in_days - 1) DAY)
                             GROUP BY product_id) c ON b.product_id = c.product_id").
      select("COALESCE(rented_qty, 0) as rented_qty, (SUM(b.stock) - COALESCE(rented_qty, 0)) as remain")
  }
#  scope :stocks_at, lambda { |date|
#    stocks.joins("LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
#                             FROM rented_products a
#                             LEFT JOIN orders b ON a.order_id = b.id
#                             WHERE b.delivery_date = '#{date}'
#                             GROUP BY product_id) c ON b.product_id = c.product_id#").
#      select("COALESCE(rented_qty, 0) as rented_qty, (SUM(b.stock) - COALESCE(rented_qty, 0)) as remain")
#  }

  def package_stock(date)
    product = Product.find_by_sql("SELECT MIN(remain) as remain
                           FROM
                           (SELECT SUM(stock) -  COALESCE(rented_qty, 0) as remain
                           FROM (SELECT child_id FROM product_packages WHERE parent_id = #{self.id}) a
                                      LEFT JOIN product_stocks b ON a.child_id = b.product_id
                                      LEFT JOIN  (SELECT product_id, SUM(rented_qty) as rented_qty
                                                         FROM rented_products a LEFT JOIN orders b ON a.order_id = b.id
                                                         WHERE '#{date}' BETWEEN b.delivery_date AND DATE_ADD(b.usage_date, INTERVAL (b.duration_in_days - 1) DAY)
                                                         GROUP BY product_id) c ON b.product_id = c.product_id
                           GROUP BY b.product_id) a")
    product.first.remain
  end

#  def available_for_package
#    Product.where("products.id = ? AND child_id IS NULL", self.id).
#            joins("LEFT JOIN (SELECT child_id
#                              FROM product_packages
#                              WHERE parent_id = #{self.id}) b ON products.id = b.child_id#")
#  end

  scope :available_for_package, lambda { |id|
    where("products.id != ? AND child_id IS NULL", id).
    joins("LEFT JOIN (SELECT child_id
                      FROM product_packages
                      WHERE parent_id = #{id}) b ON products.id = b.child_id")
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  #  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.where("name LIKE ?", "%#{params[:name]}%")
    @products = @products.where("is_package = ?", params[:is_package] == 'true' ? 1 : 0) unless params[:is_package].blank?
    @products = @products.page(params[:page]).per(10).order("created_at DESC")
    
    @product = Product.new(:name => params[:name], :is_package => params[:is_package])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @product_packages = ProductPackage.where(:parent_id => params[:id])
    @product_images = ProductImage.where(:product_id => params[:id])
    @product_image = @product.product_images.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @product_categories = ProductCategory.arrange
    render :layout => false
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @product_categories = ProductCategory.arrange
    #    render layout: false
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        unless params[:image].blank?
          @product_image = ProductImage.new(:image => params[:image], :product_id => @product.id)
          @product_image.save
        end
        format.html { redirect_to @product, :notice => "Product was successfully created. #{link_add_product}".html_safe }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.triggered_update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        #        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.triggered_destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  def order
    @ordered_product = OrderedProduct.new(:user_id => current_user.id,
      :product_id => params[:id],
      :qty => 1)
  end

  #  def save_order
  #    @product = Product.find(params[:id])
  #    @ordered_product = OrderedProduct.where(:user_id => current_user.id, :product_id => params[:id])
  #
  #    unless @ordered_product.blank?
  #      @ordered_product.update_attribute(:qty => @ordered_product.qty + 1,
  #                                        :sub_total => @product.rent_price * (@ordered_product.qty + 1))
  #    else
  #      @ordered_product = OrderedProduct.new(:user_id => current_user.id,
  #                                            :product_id => params[:id],
  #                                            :qty => 1,
  #                                            :sub_total => @product.rent_price)
  #    end
  #    @ordered_product.save
  #
  #    respond_to do |format|
  #      format.html { redirect_to admin_products_url }
  #      format.js
  #    end
  #  end
  private
  def link_add_product
    "<div class='btn'>#{view_context.link_to('Tambah Barang', new_product_path, :rel => 'facebox')}</div>"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
  <fieldset>
    <legend>&nbsp;&nbsp;&nbsp;<%= action %> Produk</legend>

  <%#= render :partial => 'layouts/partials/error_messages', :locals => { :obj => @product } %>

    <div class="control-group">
      <%= f.label 'Kategori', :class => 'control-label' %>
      <div class="controls">
        <%= f.select :product_category_id, 
                      options_for_select(nested_product_categories_options(@product_categories), @product.product_category_id) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Nama Barang', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'textfield' %>
      </div>
    </div>

    <%#*<div class="control-group">%>
      <%#= f.label 'Paket Barang', :class => 'control-label' %>
      <%#*<div class="controls">%>
        <%#= f.check_box :is_package, :class => 'check-box' %>
        <%#*&nbsp;<br />%>
      <%#*</div>%>
    <%#*</div>%>

    <div class="control-group">
      <%= f.label 'Deskripsi', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'input-xlarge', :rows => 5 %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label 'Harga', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :price, :class => 'textfield' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Gambar', :class => 'control-label' %>
      <div class="controls">
        <%= file_field_tag :image, :class => 'input-file' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Simpan', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/products/_products_table.html.erb
<table class="table table-striped">
  <thead>
  <th>Nama Produk</th>
  <th>Deskripsi</th>
  <th>Harga Beli</th>
  <th colspan="5"></th>
</thead>
<tbody>
<% @products.each do |product| %>
  <tr class="<%= cycle('odd', '') %>">
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td class="right"><%= money_format(product.price) %></td>
    <td class="iconed_text">
      <%= link_to 'Lihat', product, :class => 'btn btn-mini' %>
      <%= link_to 'Ubah', edit_product_path(product), :rel => 'facebox', :class => 'btn btn-mini' %>
      <%= link_to iconed_text('Hapus', 'icon-trash'), product, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
<tr>
  <td class="center" colspan="10"><%= paginate @products %></td>
</tr>
</tbody>
</table>

app/views/products/_search.html.erb
  <%= form_tag products_path, :class => "well form-search", :method => :get, :remote => true do %>
    <%= render :partial => 'search_form' %>
  <% end %>

app/views/products/_search_form.html.erb
<%= text_field_tag :name, @product.name, :placeholder => 'nama barang', :class => "input-medium search-query" %>

<%= select_tag :is_package, options_for_select({"Dua-duanya" => "",
    "Paket" => "true",
    "Non Paket" => "false"}, :selected => "#{@product.is_package}"), :class => "input-medium search-query" %>

<%= submit_tag 'Cari', :id => 'search_button', :class => 'btn' %>

app/views/products/_show.html.erb
<%#*<div class="span6">%>
<legend>Detail Barang</legend>
<%
data = []
data << ["Nama Barang", product.name]
data << ["Deskripsi", product.description]
data << ["Kategori", product.product_category.blank? ? "" : product.product_category.name]
data << ["Harga Baru", product.price]
%>

<%= show(data).html_safe %>
<br/>

<%
main_path = "http://#{request.host}"
main_path << ":#{request.port.to_s}" unless request.port.blank?

str = "p[title]=#{product.name}&amp;"
str << "p[title]=#{product.name}&amp;"
str << "p[url]=#{main_path}#{request.fullpath}&amp;"
str << "p[images][0]=#{main_path}#{@product_images.first.image}&amp;" unless @product_images.blank?
str << "p[summary]=#{product.description}"

%>


<a href="https://twitter.com/hilmanzaky" class="twitter-follow-button" data-show-count="false">Follow @hilmanzaky</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<script type="text/javascript">
  var addthis_share = 
    { 
    templates: {
      twitter: '<%= product.name %> {{url}}'
    }
  }
</script>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
  <a href="http://www.facebook.com/sharer.php?s= 100&amp;<%= str.html_safe %>" target="_blank">
    <span class=" at300bs at15nc at15t_facebook"><span class="at_a11y">Share on facebook</span></span>
  </a>
  <a class="addthis_button_twitter"></a>
  <a class="addthis_button_email"></a>
  <a class="addthis_button_print"></a>
  <a class="addthis_button_compact"></a>
  <a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-501240545ed408a0"></script>
<!-- AddThis Button END -->

<br/>

app/views/products/edit.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span6">
  <%= render :partial => 'form', :locals => { :action => "Ubah" } %>
</div>
  <div class="span2"></div>
</div>

app/views/products/index.html.erb
<%#*<legend>Daftar Barang</legend>%>

<%= render :partial => 'search' %>

  <%= render :partial => 'products_table' %>

  <%= link_to 'Tambah Barang', new_product_path, :rel => 'facebox', :class => 'btn', if can? :create, @products %>

app/views/products/index.js.erb
$('#products_table').html('<%= escape_javascript(render :partial => "products_table") %>');
$.setAjaxPagination();

app/views/products/new.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span6">
    <%= render :partial => 'form', :locals => { :action => "Tambah" } %>
  </div>
  <div class="span2"></div>
</div>

app/views/products/order.html.erb
<div class="panel">
  <div class="header">&nbsp;</div>

  <%= form_for(@ordered_product) do |f| %>
    <div class="main-content">
      <div class="form">
        <%= f.label 'Produk' %>&nbsp;
        <%= f.hidden_field :product_id %><br/>
        <div class="show"><%= @ordered_product.product.name %></div><br/>

        <%= f.label 'Quantity' %>&nbsp;
        <%= f.text_area :qty %><br/>

        <%= f.label 'Deskripsi' %>&nbsp;
        <%= f.text_area :description %><br/>
      </div>
    </div>
  
    <div class="footer">
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/products/show.html.erb
<div class="row">
  <div class="span6">
    <%= render :partial => 'product_images/form' if can? :create, @product_image %>
    <%= render :partial => 'product_images/list' %>
  </div>
  <div class="span6">
    <%= render :partial => 'show', :locals => { :product => @product, :product_images => @product_images } %>
    <%= link_to 'Ubah', edit_product_path(@product), :class => 'btn' if can? :update, @product %>
    <%#= link_to 'Kembali', products_path, :class => 'btn' %>
    <%= link_to 'Kembali', :back, :class => 'btn' %>
  </div>
</div>