config/routes.rb
BlackstarStdWeb::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :header_links
  
  resources :users, :only => [:show, :index]

  resources :main_sliders

  resources :product_images, :only => [:show, :create, :destroy]

  resources :product_categories

  resources :infos

  resources :products

  resources :product do
    resources :product_packages, :only => [:new, :destroy]
  end

  resources :product_packages, :only => [:create]

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :content, :title, :header_link_id, :highlight

  extend FriendlyId
  friendly_id :title, :use => :slugged

  belongs_to :header_link
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  load_and_authorize_resource
  
  def index
    @infos = Info.all
  end

  def show
    @info = Info.find(params[:id])
  end

  def new
    @info = Info.new
  end

  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        flash[:notice] = 'Info telah disimpan'
        format.html { redirect_to infos_path }
      else
#        flash[:error] = 'Kategori Barang tidak dapat dihapus'
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @info = Info.find(params[:id])
  end

  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to infos_path, :notice => 'Info telah diubah.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @info = Info.find(params[:id])

    if @info.destroy
      flash[:notice] = 'Info telah berhasil dihapus'
    else
      flash[:error] = 'Info tidak dapat dihapus'
    end

    respond_to do |format|
      format.html { redirect_to infos_path}
    end
  end
end

app/views/infos/_form.html.erb
<%= form_for(@info, :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
  <fieldset>
    <legend>Tambah Info</legend>

    <div class="control-group">
      <%= f.label 'Link Header', :class => 'control-label' %>
      <div class="controls">
        <%= f.select :header_link_id, options_from_collection_for_select(HeaderLink.all, :id, :name), :include_blank => true %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Judul', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'textfield' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Isi', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Highlight', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :highlight, :class => "tinymce", :rows => 20, :cols => 120 %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Simpan', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/infos/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "tinymce-jquery" %>
<% end %>
<div class="row">
  <div class="span12">
<%= render :partial => 'form', :locals => { :action => "edit" } %>
    </div>
</div>
<%= tinymce %>

app/views/infos/index.html.erb
<legend>Info</legend>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Judul</th>
      <th>Isi</th>
    </tr>
  </thead>
  <tbody>
    <% @infos.each do |i| %>
      <tr>
        <td><%= i.title %></td>
        <td><%= i.content.html_safe unless i.content.blank? %></td>
        <td>
          <%= link_to 'Lihat', i, :class => 'btn btn-mini' %>
          <%= link_to 'Ubah', edit_info_path(i), :class => 'btn btn-mini' %>
          <%= link_to iconed_text('Hapus', 'icon-trash'), i, :method => :delete, :confirm => 'Apakah anda yakin?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Tambah', new_info_path, :class => 'btn' %>

app/views/infos/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "tinymce-jquery" %>
<% end %>
<div class="row">
<div class="span12">
  <%= render :partial => 'form', :locals => { :action => "new" } %>
</div>
  </div>
<%= tinymce %>

app/views/infos/show.html.erb
<div class="row">
  <div class="span12">
    <legend><%= @info.title %></legend>

    <%= @info.content.html_safe unless @info.content.blank? %>

    <br/>

    <%= link_to 'Edit', edit_info_path(@info), :class => 'btn' if can? :update, @info %>
    <%= link_to iconed_text('Hapus', 'icon-trash'), @info, :method => :delete, :confirm => 'Apakah anda yakin?', :class => 'btn btn-danger' if can? :destroy, @info %>
  </div>
</div>