config/routes.rb
BlackstarStdWeb::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :header_links
  
  resources :users, :only => [:show, :index]

  resources :main_sliders

  resources :product_images, :only => [:show, :create, :destroy]

  resources :product_categories

  resources :infos

  resources :products

  resources :product do
    resources :product_packages, :only => [:new, :destroy]
  end

  resources :product_packages, :only => [:create]

end

app/views/layouts/_company_name.html.erb
<%= link_to 'DeltaPesta', root_path, :class => 'brand' %>

app/views/layouts/_contact.html.erb
<%= link_to '0856 5928 9395', '#', :class => 'contact' %>

app/views/layouts/_flash.html.erb
<% error = devise_error_messages! %>
<% if !flash.blank? %>
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
<% elsif error != "" %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, error, :id => "flash_error" if error.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <%#*<p>Put together in less than five minutes by <a href="http://www.martinbean.co.uk/" rel="author">Martin Bean</a>. Uses <a href="http://twitter.github.com/bootstrap/" rel="external">Twitter Bootstrap</a> and <a href="http://ryanfait.com/sticky-footer/" rel="external">Ryan Fait&rsquo;s Sticky Footer</a>.</p>%>
    
  </div>
  <div class="boy_left">
    <a href="#"><div class="facebook"></div></a>
  </div>
  <div class="boy_right">
    <a href="#"><div class="twitter"></div></a>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li class="divider-vertical"></li>
  <% if current_user %>
    <% if current_user.is == 'admin' %>
      <li>
        <%= link_to('Beranda', root_path) %>
      </li>
      <li>
        <%= link_to('Daftar Barang', products_path) %>
      </li>
      <li>
        <%= link_to('Kategori Barang', product_categories_path) %>
      </li>
      <li>
        <%= link_to('Link Header', header_links_path) %>
      </li>
      <li>
        <%= link_to('Info', infos_path) %>
      </li>
    <% end %>
  <% else %>
    <% HeaderLink.all.each do |hl| %>
      <li>
        <%= link_to(hl.name, hl) %>
      </li>
    <% end %>
  <% end %>
</ul>


<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li class="divider-vertical"></li>
    <li class="dropdown">
      <%= link_to('#', :class => 'dropdown-toggle', "data-toggle" => 'dropdown') do %>
        <%= current_user.email %>
        <b class ="caret"></b>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to('Edit account', edit_user_registration_path) %></li>
        <li class="divider"></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => 'delete') %></li>
      </ul>
    </li>
  <% else %>
    <li class="divider-vertical"></li>
    <li><%= render :partial => 'layouts/contact' %></li>
    <%#*<li>%>
      <%#= link_to('Login', new_user_session_path) %>
    <%#*</li>%>
    <%#*<li>%>
      <%#= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
    <%#*</li>%>
    <%#*<li>%>
      <%#= link_to('Sign up', new_user_registration_path)  %>
    <%#*</li>%>
  <% end %>
</ul>

app/views/layouts/_sub_navigation.html.erb
<header id="overview" class="jumbotron subhead">
  <div class="subnav">
    <%= nested_product_categories_nav(ProductCategory.arrange) %>
    <%#*<ul id="nav">%>
      <%#*<li>%>
        <%#*<a href="#" data-toggle="dropdown" class="dropdown-toggle">Buttons <b class="caret"></b></a>%>
        <%#*<ul>%>
          <%#*<li><a href="#buttonGroups">Button groups</a></li>%>
          <%#*<li><a href="#buttonDropdowns">Button dropdowns</a></li>%>
        <%#*</ul>%>
      <%#*</li>%>
      <%#*<li>%>
        <%#*<a href="#" data-toggle="dropdown" class="dropdown-toggle">Navigation <b class="caret"></b></a>%>
        <%#*<ul>%>
          <%#*<li><a href="#navs">Nav, tabs, pills</a></li>%>
          <%#*<li><a href="#navbar">Navbar</a></li>%>
          <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
          <%#*<li>%>
            <%#*<a href="#pagination">Pagination</a>%>
            <%#*<ul>%>
              <%#*<li><a href="#navbar">Navbar</a></li>%>
              <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
              <%#*<li>%>
                <%#*<a href="#pagination">Pagination</a>%>
                <%#*<ul>%>
                  <%#*<li><a href="#navbar">Navbar</a></li>%>
                  <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
                <%#*</ul>%>
              <%#*</li>%>
            <%#*</ul>%>
          <%#*</li>%>
        <%#*</ul>%>
      <%#*</li>%>
      <%#*<li><a href="#labels">Labels</a></li>%>
      <%#*<li><a href="#badges">Badges</a></li>%>
      <%#*<li><a href="#typography">Typography</a></li>%>
      <%#*<li><a href="#thumbnails">Thumbnails</a></li>%>
      <%#*<li><a href="#alerts">Alerts</a></li>%>
      <%#*<li><a href="#progress">Progress bars</a></li>%>
      <%#*<li><a href="#misc">Miscellaneous</a></li>%>
    <%#*</ul>%>
  </div>
</header>
<%#*<header id="overview" class="jumbotron subhead">%>
  <%#*<div class="subnav">%>
    <%#*<ul class="nav nav-pills">%>
      <%#*<li class="dropdown">%>
        <%#*<a href="#" data-toggle="dropdown" class="dropdown-toggle">Buttons <b class="caret"></b></a>%>
        <%#*<ul class="dropdown-menu">%>
          <%#*<li class="active"><a href="#buttonGroups">Button groups</a></li>%>
          <%#*<li class=""><a href="#buttonDropdowns">Button dropdowns</a></li>%>
        <%#*</ul>%>
      <%#*</li>%>
      <%#*<li class="dropdown">%>
        <%#*<a href="#" data-toggle="dropdown" class="dropdown-toggle">Navigation <b class="caret"></b></a>%>
        <%#*<ul class="dropdown-menu">%>
          <%#*<li class=""><a href="#navs">Nav, tabs, pills</a></li>%>
          <%#*<li><a href="#navbar">Navbar</a></li>%>
          <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
          <%#*<li class="dropdown">%>
            <%#*<a href="#pagination">Pagination</a>%>
            <%#*<ul class="dropdown-menu">%>
              <%#*<li><a href="#navbar">Navbar</a></li>%>
              <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
              <%#*<li class="dropdown">%>
                <%#*<a href="#pagination">Pagination</a>%>
                <%#*<ul class="dropdown-menu">%>
                  <%#*<li><a href="#navbar">Navbar</a></li>%>
                  <%#*<li><a href="#breadcrumbs">Breadcrumbs</a></li>%>
                <%#*</ul>%>
              <%#*</li>%>
            <%#*</ul>%>
          <%#*</li>%>
        <%#*</ul>%>
      <%#*</li>%>
      <%#*<li><a href="#labels">Labels</a></li>%>
      <%#*<li><a href="#badges">Badges</a></li>%>
      <%#*<li><a href="#typography">Typography</a></li>%>
      <%#*<li><a href="#thumbnails">Thumbnails</a></li>%>
      <%#*<li><a href="#alerts">Alerts</a></li>%>
      <%#*<li><a href="#progress">Progress bars</a></li>%>
      <%#*<li><a href="#misc">Miscellaneous</a></li>%>
    <%#*</ul>%>
  <%#*</div>%>
<%#*</header>%>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "DeltaPesta" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag "jquery.facebox.css" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= render :partial => 'layouts/company_name' %>
          <div class="nav-collapse">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </div>
    <div class="wrapper">
    <div id="main" role="main">
      <div class="container">
<%#*<div class="content">%>
        <%= render :partial => 'layouts/sub_navigation' %>
        <%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>
        <%= yield %>
<%#*</div>%>
      </div> <!--! end of .container -->
      <div class="push"><!--//--></div>
    </div> <!--! end of #main -->
    <%= render :partial => 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "DeltaPesta" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
<%#*<a class="brand" href="#">Some Store</a>%>
          <%= render :partial => 'layouts/company_name' %>

          <div class="nav-collapse">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </div>
    <div class="wrapper">
      <div id="main" role="main">
        <div class="container">
          <%= render :partial => 'layouts/sub_navigation' %>
          <%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>
          <%= yield %>

<%#*<div class="content">%>
<%#*<footer>%>
<%#*</footer>%>
<%#*</div>%>
        </div> <!--! end of .container -->
        <div class="push"><!--//--></div>
      </div> <!--! end of #main -->
      <%= render :partial => 'layouts/footer' %>

    </div> 
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlackstarRentApp</title>
    <%= stylesheet_link_tag "style", "incomplete" %>
    <%= stylesheet_link_tag "print", :media => 'screen, print' %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "print" %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <table width="100%">
      <tr>
        <td>
          <div id="print" class="print"><%= link_to("Print", "#") %></div>
          <%= yield %>
        </td>
      </tr>
    </table>
  </body>
</html>